sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
      - udf_coverage
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.24.0"
    - "7.1.26"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
